services:
  api:
    build: ./
    command: sh -c "concurrently \"npm run ${SCRIPT:-start}\" \"npm run codegen\""
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    expose: 
      - 8000
    networks:
      postgres: 
    depends_on:
      db:
        condition: service_healthy

  client:
    build: ../2209-wns-hamilton-winterent-front
    depends_on:
      - api
    volumes:
      - ../2209-wns-hamilton-winterent-front:/app
    ports:
      - 3000:3000
    expose:
      - 3000

  db:
    image: postgres
    restart: always
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 300s
      retries: 25
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: winterent
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      postgres:
    expose:
      - "5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      postgres:

networks:
  postgres:
volumes:
  database: