name: test-ci

on:
  push:
    branches:
      - 'Feature/CI'

jobs:

  test-back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: build app
        run: docker compose -f docker-compose-build-back.yml up --build --detach
      - name: Wait for build to finish
        run: echo "Build terminé !"
        if: ${{ steps.build.outcome == 'success' }}
      - name: test
        run: npm i && npm run testDev


  deploy:

    runs-on: ubuntu-latest

    steps:
   
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
     
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
     
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_HUB_SERVER_IMAGE_NAME_STAGING }}:latest
