name: test-ci

on:
  push:
    branches:
      - 'Feature/test'

jobs:
  test-back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: build app
        run: docker compose up --build 
      #   id: build
      # - name: Wait for build to finish
      #   run: echo "Build finished!"
      #   # Attendre la fin du build en utilisant le résultat de l'étape précédente
      #   if: ${{ steps.build.outcome == 'success' }}
      # - name: test
      #   uses: run test

